/**
 * generated by Xtext 2.13.0
 */
package beleg;

import beleg.AbstractS78154S78236RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class S78154S78236RuntimeModule extends AbstractS78154S78236RuntimeModule {
}
