/**
 * generated by Xtext 2.13.0
 */
package beleg;

import beleg.S78154S78236StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class S78154S78236StandaloneSetup extends S78154S78236StandaloneSetupGenerated {
  public static void doSetup() {
    new S78154S78236StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
