/**
 * generated by Xtext 2.13.0
 */
package beleg.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
@SuppressWarnings("all")
public class S78154S78236OutlineTreeProvider extends DefaultOutlineTreeProvider {
}
