/*
 * generated by Xtext 2.13.0
 */
package beleg


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class S78154S78236StandaloneSetup extends S78154S78236StandaloneSetupGenerated {

	def static void doSetup() {
		new S78154S78236StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
