/*
 * generated by Xtext 2.13.0
 */
package beleg.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class S78154S78236UiModule extends AbstractS78154S78236UiModule {
}
