/*
 * generated by Xtext 2.13.0
 */
package beleg.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractS78154S78236Validator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(beleg.s78154S78236.S78154S78236Package.eINSTANCE);
		return result;
	}
	
}
