/**
 * generated by Xtext 2.13.0
 */
package beleg.ui;

import beleg.ui.AbstractS78154S78236UiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class S78154S78236UiModule extends AbstractS78154S78236UiModule {
  public S78154S78236UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
