/**
 * generated by Xtext 2.13.0
 */
package beleg.s78154S78236.impl;

import beleg.s78154S78236.Exquery;
import beleg.s78154S78236.Program;
import beleg.s78154S78236.PrologDsl;
import beleg.s78154S78236.S78154S78236Package;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Prolog Dsl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link beleg.s78154S78236.impl.PrologDslImpl#getProgram <em>Program</em>}</li>
 *   <li>{@link beleg.s78154S78236.impl.PrologDslImpl#getExQuery <em>Ex Query</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class PrologDslImpl extends MinimalEObjectImpl.Container implements PrologDsl
{
  /**
   * The cached value of the '{@link #getProgram() <em>Program</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProgram()
   * @generated
   * @ordered
   */
  protected Program program;

  /**
   * The cached value of the '{@link #getExQuery() <em>Ex Query</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExQuery()
   * @generated
   * @ordered
   */
  protected Exquery exQuery;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrologDslImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return S78154S78236Package.Literals.PROLOG_DSL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Program getProgram()
  {
    return program;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetProgram(Program newProgram, NotificationChain msgs)
  {
    Program oldProgram = program;
    program = newProgram;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, S78154S78236Package.PROLOG_DSL__PROGRAM, oldProgram, newProgram);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setProgram(Program newProgram)
  {
    if (newProgram != program)
    {
      NotificationChain msgs = null;
      if (program != null)
        msgs = ((InternalEObject)program).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - S78154S78236Package.PROLOG_DSL__PROGRAM, null, msgs);
      if (newProgram != null)
        msgs = ((InternalEObject)newProgram).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - S78154S78236Package.PROLOG_DSL__PROGRAM, null, msgs);
      msgs = basicSetProgram(newProgram, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, S78154S78236Package.PROLOG_DSL__PROGRAM, newProgram, newProgram));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Exquery getExQuery()
  {
    return exQuery;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExQuery(Exquery newExQuery, NotificationChain msgs)
  {
    Exquery oldExQuery = exQuery;
    exQuery = newExQuery;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, S78154S78236Package.PROLOG_DSL__EX_QUERY, oldExQuery, newExQuery);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExQuery(Exquery newExQuery)
  {
    if (newExQuery != exQuery)
    {
      NotificationChain msgs = null;
      if (exQuery != null)
        msgs = ((InternalEObject)exQuery).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - S78154S78236Package.PROLOG_DSL__EX_QUERY, null, msgs);
      if (newExQuery != null)
        msgs = ((InternalEObject)newExQuery).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - S78154S78236Package.PROLOG_DSL__EX_QUERY, null, msgs);
      msgs = basicSetExQuery(newExQuery, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, S78154S78236Package.PROLOG_DSL__EX_QUERY, newExQuery, newExQuery));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case S78154S78236Package.PROLOG_DSL__PROGRAM:
        return basicSetProgram(null, msgs);
      case S78154S78236Package.PROLOG_DSL__EX_QUERY:
        return basicSetExQuery(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case S78154S78236Package.PROLOG_DSL__PROGRAM:
        return getProgram();
      case S78154S78236Package.PROLOG_DSL__EX_QUERY:
        return getExQuery();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case S78154S78236Package.PROLOG_DSL__PROGRAM:
        setProgram((Program)newValue);
        return;
      case S78154S78236Package.PROLOG_DSL__EX_QUERY:
        setExQuery((Exquery)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case S78154S78236Package.PROLOG_DSL__PROGRAM:
        setProgram((Program)null);
        return;
      case S78154S78236Package.PROLOG_DSL__EX_QUERY:
        setExQuery((Exquery)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case S78154S78236Package.PROLOG_DSL__PROGRAM:
        return program != null;
      case S78154S78236Package.PROLOG_DSL__EX_QUERY:
        return exQuery != null;
    }
    return super.eIsSet(featureID);
  }

} //PrologDslImpl
