/*
 * generated by Xtext 2.13.0
 */
package beleg.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class S78154S78236AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("beleg/parser/antlr/internal/InternalS78154S78236.tokens");
	}
}
