/**
 * generated by Xtext 2.13.0
 */
package beleg.validation;

import beleg.validation.AbstractS78154S78236Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class S78154S78236Validator extends AbstractS78154S78236Validator {
}
