/**
 * generated by Xtext 2.13.0
 */
package beleg.ide;

import beleg.ide.AbstractS78154S78236IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class S78154S78236IdeModule extends AbstractS78154S78236IdeModule {
}
