/*
 * generated by Xtext 2.13.0
 */
package beleg.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class S78154S78236ProposalProvider extends AbstractS78154S78236ProposalProvider {
}
