/**
 * generated by Xtext 2.13.0
 */
package beleg.s78154S78236;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atom</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link beleg.s78154S78236.Atom#getIdent <em>Ident</em>}</li>
 *   <li>{@link beleg.s78154S78236.Atom#getNumber <em>Number</em>}</li>
 *   <li>{@link beleg.s78154S78236.Atom#getEvar <em>Evar</em>}</li>
 * </ul>
 * </p>
 *
 * @see beleg.s78154S78236.S78154S78236Package#getAtom()
 * @model
 * @generated
 */
public interface Atom extends EObject
{
  /**
   * Returns the value of the '<em><b>Ident</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ident</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ident</em>' containment reference.
   * @see #setIdent(Ident)
   * @see beleg.s78154S78236.S78154S78236Package#getAtom_Ident()
   * @model containment="true"
   * @generated
   */
  Ident getIdent();

  /**
   * Sets the value of the '{@link beleg.s78154S78236.Atom#getIdent <em>Ident</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ident</em>' containment reference.
   * @see #getIdent()
   * @generated
   */
  void setIdent(Ident value);

  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Number</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(String)
   * @see beleg.s78154S78236.S78154S78236Package#getAtom_Number()
   * @model
   * @generated
   */
  String getNumber();

  /**
   * Sets the value of the '{@link beleg.s78154S78236.Atom#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(String value);

  /**
   * Returns the value of the '<em><b>Evar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Evar</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Evar</em>' containment reference.
   * @see #setEvar(EVar)
   * @see beleg.s78154S78236.S78154S78236Package#getAtom_Evar()
   * @model containment="true"
   * @generated
   */
  EVar getEvar();

  /**
   * Sets the value of the '{@link beleg.s78154S78236.Atom#getEvar <em>Evar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Evar</em>' containment reference.
   * @see #getEvar()
   * @generated
   */
  void setEvar(EVar value);

} // Atom
