/**
 * generated by Xtext 2.13.0
 */
package beleg.s78154S78236;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EFolge</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link beleg.s78154S78236.EFolge#getFolge <em>Folge</em>}</li>
 * </ul>
 * </p>
 *
 * @see beleg.s78154S78236.S78154S78236Package#getEFolge()
 * @model
 * @generated
 */
public interface EFolge extends EObject
{
  /**
   * Returns the value of the '<em><b>Folge</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Folge</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Folge</em>' containment reference.
   * @see #setFolge(Folge)
   * @see beleg.s78154S78236.S78154S78236Package#getEFolge_Folge()
   * @model containment="true"
   * @generated
   */
  Folge getFolge();

  /**
   * Sets the value of the '{@link beleg.s78154S78236.EFolge#getFolge <em>Folge</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Folge</em>' containment reference.
   * @see #getFolge()
   * @generated
   */
  void setFolge(Folge value);

} // EFolge
