/**
 * generated by Xtext 2.13.0
 */
package beleg.s78154S78236;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Empty List</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see beleg.s78154S78236.S78154S78236Package#getEmptyList()
 * @model
 * @generated
 */
public interface EmptyList extends EObject
{
} // EmptyList
