/**
 * generated by Xtext 2.13.0
 */
package beleg.s78154S78236;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link beleg.s78154S78236.List#getEmpty <em>Empty</em>}</li>
 *   <li>{@link beleg.s78154S78236.List#getNonEmptyList <em>Non Empty List</em>}</li>
 * </ul>
 * </p>
 *
 * @see beleg.s78154S78236.S78154S78236Package#getList()
 * @model
 * @generated
 */
public interface List extends EObject
{
  /**
   * Returns the value of the '<em><b>Empty</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Empty</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Empty</em>' containment reference.
   * @see #setEmpty(EmptyList)
   * @see beleg.s78154S78236.S78154S78236Package#getList_Empty()
   * @model containment="true"
   * @generated
   */
  EmptyList getEmpty();

  /**
   * Sets the value of the '{@link beleg.s78154S78236.List#getEmpty <em>Empty</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Empty</em>' containment reference.
   * @see #getEmpty()
   * @generated
   */
  void setEmpty(EmptyList value);

  /**
   * Returns the value of the '<em><b>Non Empty List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Non Empty List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Non Empty List</em>' containment reference.
   * @see #setNonEmptyList(NonEmptyList)
   * @see beleg.s78154S78236.S78154S78236Package#getList_NonEmptyList()
   * @model containment="true"
   * @generated
   */
  NonEmptyList getNonEmptyList();

  /**
   * Sets the value of the '{@link beleg.s78154S78236.List#getNonEmptyList <em>Non Empty List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Non Empty List</em>' containment reference.
   * @see #getNonEmptyList()
   * @generated
   */
  void setNonEmptyList(NonEmptyList value);

} // List
