/**
 * generated by Xtext 2.13.0
 */
package beleg.s78154S78236;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see beleg.s78154S78236.S78154S78236Factory
 * @model kind="package"
 * @generated
 */
public interface S78154S78236Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "s78154S78236";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.S78154S78236.beleg";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "s78154S78236";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  S78154S78236Package eINSTANCE = beleg.s78154S78236.impl.S78154S78236PackageImpl.init();

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.ModelImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Model</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.PrologDslImpl <em>Prolog Dsl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.PrologDslImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getPrologDsl()
   * @generated
   */
  int PROLOG_DSL = 1;

  /**
   * The feature id for the '<em><b>Program</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROLOG_DSL__PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Ex Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROLOG_DSL__EX_QUERY = 1;

  /**
   * The number of structural features of the '<em>Prolog Dsl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROLOG_DSL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.ProgramImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 2;

  /**
   * The feature id for the '<em><b>Clauses</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__CLAUSES = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.ExqueryImpl <em>Exquery</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.ExqueryImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getExquery()
   * @generated
   */
  int EXQUERY = 3;

  /**
   * The feature id for the '<em><b>Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXQUERY__QUERY = 0;

  /**
   * The number of structural features of the '<em>Exquery</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXQUERY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.QueryImpl <em>Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.QueryImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getQuery()
   * @generated
   */
  int QUERY = 4;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__PREDICATE = 0;

  /**
   * The feature id for the '<em><b>Epredicates</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__EPREDICATES = 1;

  /**
   * The number of structural features of the '<em>Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.EPredicateImpl <em>EPredicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.EPredicateImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getEPredicate()
   * @generated
   */
  int EPREDICATE = 5;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPREDICATE__PREDICATE = 0;

  /**
   * The number of structural features of the '<em>EPredicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPREDICATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.ClauseImpl <em>Clause</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.ClauseImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getClause()
   * @generated
   */
  int CLAUSE = 6;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAUSE__PREDICATE = 0;

  /**
   * The feature id for the '<em><b>Fact</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAUSE__FACT = 1;

  /**
   * The feature id for the '<em><b>Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAUSE__RULE = 2;

  /**
   * The number of structural features of the '<em>Clause</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAUSE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.FactImpl <em>Fact</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.FactImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getFact()
   * @generated
   */
  int FACT = 7;

  /**
   * The number of structural features of the '<em>Fact</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.RuleImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getRule()
   * @generated
   */
  int RULE = 8;

  /**
   * The feature id for the '<em><b>Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__QUERY = 0;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.PredicateImpl <em>Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.PredicateImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getPredicate()
   * @generated
   */
  int PREDICATE = 9;

  /**
   * The feature id for the '<em><b>Functor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__FUNCTOR = 0;

  /**
   * The feature id for the '<em><b>Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__TERM = 1;

  /**
   * The feature id for the '<em><b>Eterms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__ETERMS = 2;

  /**
   * The number of structural features of the '<em>Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.FunctorImpl <em>Functor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.FunctorImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getFunctor()
   * @generated
   */
  int FUNCTOR = 10;

  /**
   * The feature id for the '<em><b>Ident</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTOR__IDENT = 0;

  /**
   * The number of structural features of the '<em>Functor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.TermImpl <em>Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.TermImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getTerm()
   * @generated
   */
  int TERM = 11;

  /**
   * The feature id for the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM__ATOM = 0;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM__LIST = 1;

  /**
   * The number of structural features of the '<em>Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.ETermImpl <em>ETerm</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.ETermImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getETerm()
   * @generated
   */
  int ETERM = 12;

  /**
   * The feature id for the '<em><b>Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ETERM__TERM = 0;

  /**
   * The number of structural features of the '<em>ETerm</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ETERM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.AtomImpl <em>Atom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.AtomImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getAtom()
   * @generated
   */
  int ATOM = 13;

  /**
   * The feature id for the '<em><b>Ident</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__IDENT = 0;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__NUMBER = 1;

  /**
   * The feature id for the '<em><b>Evar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__EVAR = 2;

  /**
   * The number of structural features of the '<em>Atom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.ListImpl <em>List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.ListImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getList()
   * @generated
   */
  int LIST = 14;

  /**
   * The feature id for the '<em><b>Empty</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST__EMPTY = 0;

  /**
   * The feature id for the '<em><b>Non Empty List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST__NON_EMPTY_LIST = 1;

  /**
   * The number of structural features of the '<em>List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.EmptyListImpl <em>Empty List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.EmptyListImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getEmptyList()
   * @generated
   */
  int EMPTY_LIST = 15;

  /**
   * The number of structural features of the '<em>Empty List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPTY_LIST_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.NonEmptyListImpl <em>Non Empty List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.NonEmptyListImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getNonEmptyList()
   * @generated
   */
  int NON_EMPTY_LIST = 16;

  /**
   * The feature id for the '<em><b>Efolge</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_EMPTY_LIST__EFOLGE = 0;

  /**
   * The feature id for the '<em><b>Elist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_EMPTY_LIST__ELIST = 1;

  /**
   * The number of structural features of the '<em>Non Empty List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_EMPTY_LIST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.FolgeImpl <em>Folge</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.FolgeImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getFolge()
   * @generated
   */
  int FOLGE = 17;

  /**
   * The feature id for the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOLGE__ATOM = 0;

  /**
   * The feature id for the '<em><b>Eatoms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOLGE__EATOMS = 1;

  /**
   * The number of structural features of the '<em>Folge</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOLGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.EFolgeImpl <em>EFolge</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.EFolgeImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getEFolge()
   * @generated
   */
  int EFOLGE = 18;

  /**
   * The feature id for the '<em><b>Folge</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EFOLGE__FOLGE = 0;

  /**
   * The number of structural features of the '<em>EFolge</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EFOLGE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.EListImpl <em>EList</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.EListImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getEList()
   * @generated
   */
  int ELIST = 19;

  /**
   * The feature id for the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELIST__ATOM = 0;

  /**
   * The feature id for the '<em><b>Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELIST__TERM = 1;

  /**
   * The number of structural features of the '<em>EList</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELIST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.EAtomImpl <em>EAtom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.EAtomImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getEAtom()
   * @generated
   */
  int EATOM = 20;

  /**
   * The feature id for the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EATOM__ATOM = 0;

  /**
   * The number of structural features of the '<em>EAtom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EATOM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.IdentImpl <em>Ident</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.IdentImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getIdent()
   * @generated
   */
  int IDENT = 21;

  /**
   * The feature id for the '<em><b>Ident</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENT__IDENT = 0;

  /**
   * The number of structural features of the '<em>Ident</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link beleg.s78154S78236.impl.EVarImpl <em>EVar</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see beleg.s78154S78236.impl.EVarImpl
   * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getEVar()
   * @generated
   */
  int EVAR = 22;

  /**
   * The feature id for the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVAR__VARIABLE = 0;

  /**
   * The number of structural features of the '<em>EVar</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVAR_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see beleg.s78154S78236.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link beleg.s78154S78236.Model#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Model</em>'.
   * @see beleg.s78154S78236.Model#getModel()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Model();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.PrologDsl <em>Prolog Dsl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prolog Dsl</em>'.
   * @see beleg.s78154S78236.PrologDsl
   * @generated
   */
  EClass getPrologDsl();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.PrologDsl#getProgram <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Program</em>'.
   * @see beleg.s78154S78236.PrologDsl#getProgram()
   * @see #getPrologDsl()
   * @generated
   */
  EReference getPrologDsl_Program();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.PrologDsl#getExQuery <em>Ex Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ex Query</em>'.
   * @see beleg.s78154S78236.PrologDsl#getExQuery()
   * @see #getPrologDsl()
   * @generated
   */
  EReference getPrologDsl_ExQuery();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see beleg.s78154S78236.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link beleg.s78154S78236.Program#getClauses <em>Clauses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Clauses</em>'.
   * @see beleg.s78154S78236.Program#getClauses()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Clauses();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.Exquery <em>Exquery</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exquery</em>'.
   * @see beleg.s78154S78236.Exquery
   * @generated
   */
  EClass getExquery();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.Exquery#getQuery <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Query</em>'.
   * @see beleg.s78154S78236.Exquery#getQuery()
   * @see #getExquery()
   * @generated
   */
  EReference getExquery_Query();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.Query <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query</em>'.
   * @see beleg.s78154S78236.Query
   * @generated
   */
  EClass getQuery();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.Query#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see beleg.s78154S78236.Query#getPredicate()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_Predicate();

  /**
   * Returns the meta object for the containment reference list '{@link beleg.s78154S78236.Query#getEpredicates <em>Epredicates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Epredicates</em>'.
   * @see beleg.s78154S78236.Query#getEpredicates()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_Epredicates();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.EPredicate <em>EPredicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EPredicate</em>'.
   * @see beleg.s78154S78236.EPredicate
   * @generated
   */
  EClass getEPredicate();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.EPredicate#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see beleg.s78154S78236.EPredicate#getPredicate()
   * @see #getEPredicate()
   * @generated
   */
  EReference getEPredicate_Predicate();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.Clause <em>Clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Clause</em>'.
   * @see beleg.s78154S78236.Clause
   * @generated
   */
  EClass getClause();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.Clause#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see beleg.s78154S78236.Clause#getPredicate()
   * @see #getClause()
   * @generated
   */
  EReference getClause_Predicate();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.Clause#getFact <em>Fact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fact</em>'.
   * @see beleg.s78154S78236.Clause#getFact()
   * @see #getClause()
   * @generated
   */
  EReference getClause_Fact();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.Clause#getRule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rule</em>'.
   * @see beleg.s78154S78236.Clause#getRule()
   * @see #getClause()
   * @generated
   */
  EReference getClause_Rule();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.Fact <em>Fact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fact</em>'.
   * @see beleg.s78154S78236.Fact
   * @generated
   */
  EClass getFact();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see beleg.s78154S78236.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.Rule#getQuery <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Query</em>'.
   * @see beleg.s78154S78236.Rule#getQuery()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Query();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.Predicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate</em>'.
   * @see beleg.s78154S78236.Predicate
   * @generated
   */
  EClass getPredicate();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.Predicate#getFunctor <em>Functor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Functor</em>'.
   * @see beleg.s78154S78236.Predicate#getFunctor()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_Functor();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.Predicate#getTerm <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Term</em>'.
   * @see beleg.s78154S78236.Predicate#getTerm()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_Term();

  /**
   * Returns the meta object for the containment reference list '{@link beleg.s78154S78236.Predicate#getEterms <em>Eterms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Eterms</em>'.
   * @see beleg.s78154S78236.Predicate#getEterms()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_Eterms();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.Functor <em>Functor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Functor</em>'.
   * @see beleg.s78154S78236.Functor
   * @generated
   */
  EClass getFunctor();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.Functor#getIdent <em>Ident</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ident</em>'.
   * @see beleg.s78154S78236.Functor#getIdent()
   * @see #getFunctor()
   * @generated
   */
  EReference getFunctor_Ident();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.Term <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Term</em>'.
   * @see beleg.s78154S78236.Term
   * @generated
   */
  EClass getTerm();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.Term#getAtom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atom</em>'.
   * @see beleg.s78154S78236.Term#getAtom()
   * @see #getTerm()
   * @generated
   */
  EReference getTerm_Atom();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.Term#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>List</em>'.
   * @see beleg.s78154S78236.Term#getList()
   * @see #getTerm()
   * @generated
   */
  EReference getTerm_List();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.ETerm <em>ETerm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ETerm</em>'.
   * @see beleg.s78154S78236.ETerm
   * @generated
   */
  EClass getETerm();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.ETerm#getTerm <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Term</em>'.
   * @see beleg.s78154S78236.ETerm#getTerm()
   * @see #getETerm()
   * @generated
   */
  EReference getETerm_Term();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.Atom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atom</em>'.
   * @see beleg.s78154S78236.Atom
   * @generated
   */
  EClass getAtom();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.Atom#getIdent <em>Ident</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ident</em>'.
   * @see beleg.s78154S78236.Atom#getIdent()
   * @see #getAtom()
   * @generated
   */
  EReference getAtom_Ident();

  /**
   * Returns the meta object for the attribute '{@link beleg.s78154S78236.Atom#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see beleg.s78154S78236.Atom#getNumber()
   * @see #getAtom()
   * @generated
   */
  EAttribute getAtom_Number();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.Atom#getEvar <em>Evar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Evar</em>'.
   * @see beleg.s78154S78236.Atom#getEvar()
   * @see #getAtom()
   * @generated
   */
  EReference getAtom_Evar();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.List <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List</em>'.
   * @see beleg.s78154S78236.List
   * @generated
   */
  EClass getList();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.List#getEmpty <em>Empty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Empty</em>'.
   * @see beleg.s78154S78236.List#getEmpty()
   * @see #getList()
   * @generated
   */
  EReference getList_Empty();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.List#getNonEmptyList <em>Non Empty List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Non Empty List</em>'.
   * @see beleg.s78154S78236.List#getNonEmptyList()
   * @see #getList()
   * @generated
   */
  EReference getList_NonEmptyList();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.EmptyList <em>Empty List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Empty List</em>'.
   * @see beleg.s78154S78236.EmptyList
   * @generated
   */
  EClass getEmptyList();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.NonEmptyList <em>Non Empty List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Non Empty List</em>'.
   * @see beleg.s78154S78236.NonEmptyList
   * @generated
   */
  EClass getNonEmptyList();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.NonEmptyList#getEfolge <em>Efolge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Efolge</em>'.
   * @see beleg.s78154S78236.NonEmptyList#getEfolge()
   * @see #getNonEmptyList()
   * @generated
   */
  EReference getNonEmptyList_Efolge();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.NonEmptyList#getElist <em>Elist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elist</em>'.
   * @see beleg.s78154S78236.NonEmptyList#getElist()
   * @see #getNonEmptyList()
   * @generated
   */
  EReference getNonEmptyList_Elist();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.Folge <em>Folge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Folge</em>'.
   * @see beleg.s78154S78236.Folge
   * @generated
   */
  EClass getFolge();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.Folge#getAtom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atom</em>'.
   * @see beleg.s78154S78236.Folge#getAtom()
   * @see #getFolge()
   * @generated
   */
  EReference getFolge_Atom();

  /**
   * Returns the meta object for the containment reference list '{@link beleg.s78154S78236.Folge#getEatoms <em>Eatoms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Eatoms</em>'.
   * @see beleg.s78154S78236.Folge#getEatoms()
   * @see #getFolge()
   * @generated
   */
  EReference getFolge_Eatoms();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.EFolge <em>EFolge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EFolge</em>'.
   * @see beleg.s78154S78236.EFolge
   * @generated
   */
  EClass getEFolge();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.EFolge#getFolge <em>Folge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Folge</em>'.
   * @see beleg.s78154S78236.EFolge#getFolge()
   * @see #getEFolge()
   * @generated
   */
  EReference getEFolge_Folge();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.EList <em>EList</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EList</em>'.
   * @see beleg.s78154S78236.EList
   * @generated
   */
  EClass getEList();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.EList#getAtom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atom</em>'.
   * @see beleg.s78154S78236.EList#getAtom()
   * @see #getEList()
   * @generated
   */
  EReference getEList_Atom();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.EList#getTerm <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Term</em>'.
   * @see beleg.s78154S78236.EList#getTerm()
   * @see #getEList()
   * @generated
   */
  EReference getEList_Term();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.EAtom <em>EAtom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EAtom</em>'.
   * @see beleg.s78154S78236.EAtom
   * @generated
   */
  EClass getEAtom();

  /**
   * Returns the meta object for the containment reference '{@link beleg.s78154S78236.EAtom#getAtom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atom</em>'.
   * @see beleg.s78154S78236.EAtom#getAtom()
   * @see #getEAtom()
   * @generated
   */
  EReference getEAtom_Atom();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.Ident <em>Ident</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ident</em>'.
   * @see beleg.s78154S78236.Ident
   * @generated
   */
  EClass getIdent();

  /**
   * Returns the meta object for the attribute '{@link beleg.s78154S78236.Ident#getIdent <em>Ident</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ident</em>'.
   * @see beleg.s78154S78236.Ident#getIdent()
   * @see #getIdent()
   * @generated
   */
  EAttribute getIdent_Ident();

  /**
   * Returns the meta object for class '{@link beleg.s78154S78236.EVar <em>EVar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EVar</em>'.
   * @see beleg.s78154S78236.EVar
   * @generated
   */
  EClass getEVar();

  /**
   * Returns the meta object for the attribute '{@link beleg.s78154S78236.EVar#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variable</em>'.
   * @see beleg.s78154S78236.EVar#getVariable()
   * @see #getEVar()
   * @generated
   */
  EAttribute getEVar_Variable();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  S78154S78236Factory getS78154S78236Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.ModelImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MODEL = eINSTANCE.getModel_Model();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.PrologDslImpl <em>Prolog Dsl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.PrologDslImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getPrologDsl()
     * @generated
     */
    EClass PROLOG_DSL = eINSTANCE.getPrologDsl();

    /**
     * The meta object literal for the '<em><b>Program</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROLOG_DSL__PROGRAM = eINSTANCE.getPrologDsl_Program();

    /**
     * The meta object literal for the '<em><b>Ex Query</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROLOG_DSL__EX_QUERY = eINSTANCE.getPrologDsl_ExQuery();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.ProgramImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Clauses</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__CLAUSES = eINSTANCE.getProgram_Clauses();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.ExqueryImpl <em>Exquery</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.ExqueryImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getExquery()
     * @generated
     */
    EClass EXQUERY = eINSTANCE.getExquery();

    /**
     * The meta object literal for the '<em><b>Query</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXQUERY__QUERY = eINSTANCE.getExquery_Query();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.QueryImpl <em>Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.QueryImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getQuery()
     * @generated
     */
    EClass QUERY = eINSTANCE.getQuery();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__PREDICATE = eINSTANCE.getQuery_Predicate();

    /**
     * The meta object literal for the '<em><b>Epredicates</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__EPREDICATES = eINSTANCE.getQuery_Epredicates();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.EPredicateImpl <em>EPredicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.EPredicateImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getEPredicate()
     * @generated
     */
    EClass EPREDICATE = eINSTANCE.getEPredicate();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EPREDICATE__PREDICATE = eINSTANCE.getEPredicate_Predicate();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.ClauseImpl <em>Clause</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.ClauseImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getClause()
     * @generated
     */
    EClass CLAUSE = eINSTANCE.getClause();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLAUSE__PREDICATE = eINSTANCE.getClause_Predicate();

    /**
     * The meta object literal for the '<em><b>Fact</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLAUSE__FACT = eINSTANCE.getClause_Fact();

    /**
     * The meta object literal for the '<em><b>Rule</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLAUSE__RULE = eINSTANCE.getClause_Rule();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.FactImpl <em>Fact</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.FactImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getFact()
     * @generated
     */
    EClass FACT = eINSTANCE.getFact();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.RuleImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Query</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__QUERY = eINSTANCE.getRule_Query();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.PredicateImpl <em>Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.PredicateImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getPredicate()
     * @generated
     */
    EClass PREDICATE = eINSTANCE.getPredicate();

    /**
     * The meta object literal for the '<em><b>Functor</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__FUNCTOR = eINSTANCE.getPredicate_Functor();

    /**
     * The meta object literal for the '<em><b>Term</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__TERM = eINSTANCE.getPredicate_Term();

    /**
     * The meta object literal for the '<em><b>Eterms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__ETERMS = eINSTANCE.getPredicate_Eterms();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.FunctorImpl <em>Functor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.FunctorImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getFunctor()
     * @generated
     */
    EClass FUNCTOR = eINSTANCE.getFunctor();

    /**
     * The meta object literal for the '<em><b>Ident</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTOR__IDENT = eINSTANCE.getFunctor_Ident();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.TermImpl <em>Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.TermImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getTerm()
     * @generated
     */
    EClass TERM = eINSTANCE.getTerm();

    /**
     * The meta object literal for the '<em><b>Atom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERM__ATOM = eINSTANCE.getTerm_Atom();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERM__LIST = eINSTANCE.getTerm_List();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.ETermImpl <em>ETerm</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.ETermImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getETerm()
     * @generated
     */
    EClass ETERM = eINSTANCE.getETerm();

    /**
     * The meta object literal for the '<em><b>Term</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ETERM__TERM = eINSTANCE.getETerm_Term();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.AtomImpl <em>Atom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.AtomImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getAtom()
     * @generated
     */
    EClass ATOM = eINSTANCE.getAtom();

    /**
     * The meta object literal for the '<em><b>Ident</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATOM__IDENT = eINSTANCE.getAtom_Ident();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOM__NUMBER = eINSTANCE.getAtom_Number();

    /**
     * The meta object literal for the '<em><b>Evar</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATOM__EVAR = eINSTANCE.getAtom_Evar();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.ListImpl <em>List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.ListImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getList()
     * @generated
     */
    EClass LIST = eINSTANCE.getList();

    /**
     * The meta object literal for the '<em><b>Empty</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST__EMPTY = eINSTANCE.getList_Empty();

    /**
     * The meta object literal for the '<em><b>Non Empty List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST__NON_EMPTY_LIST = eINSTANCE.getList_NonEmptyList();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.EmptyListImpl <em>Empty List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.EmptyListImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getEmptyList()
     * @generated
     */
    EClass EMPTY_LIST = eINSTANCE.getEmptyList();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.NonEmptyListImpl <em>Non Empty List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.NonEmptyListImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getNonEmptyList()
     * @generated
     */
    EClass NON_EMPTY_LIST = eINSTANCE.getNonEmptyList();

    /**
     * The meta object literal for the '<em><b>Efolge</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NON_EMPTY_LIST__EFOLGE = eINSTANCE.getNonEmptyList_Efolge();

    /**
     * The meta object literal for the '<em><b>Elist</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NON_EMPTY_LIST__ELIST = eINSTANCE.getNonEmptyList_Elist();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.FolgeImpl <em>Folge</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.FolgeImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getFolge()
     * @generated
     */
    EClass FOLGE = eINSTANCE.getFolge();

    /**
     * The meta object literal for the '<em><b>Atom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOLGE__ATOM = eINSTANCE.getFolge_Atom();

    /**
     * The meta object literal for the '<em><b>Eatoms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOLGE__EATOMS = eINSTANCE.getFolge_Eatoms();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.EFolgeImpl <em>EFolge</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.EFolgeImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getEFolge()
     * @generated
     */
    EClass EFOLGE = eINSTANCE.getEFolge();

    /**
     * The meta object literal for the '<em><b>Folge</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EFOLGE__FOLGE = eINSTANCE.getEFolge_Folge();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.EListImpl <em>EList</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.EListImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getEList()
     * @generated
     */
    EClass ELIST = eINSTANCE.getEList();

    /**
     * The meta object literal for the '<em><b>Atom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELIST__ATOM = eINSTANCE.getEList_Atom();

    /**
     * The meta object literal for the '<em><b>Term</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELIST__TERM = eINSTANCE.getEList_Term();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.EAtomImpl <em>EAtom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.EAtomImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getEAtom()
     * @generated
     */
    EClass EATOM = eINSTANCE.getEAtom();

    /**
     * The meta object literal for the '<em><b>Atom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EATOM__ATOM = eINSTANCE.getEAtom_Atom();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.IdentImpl <em>Ident</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.IdentImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getIdent()
     * @generated
     */
    EClass IDENT = eINSTANCE.getIdent();

    /**
     * The meta object literal for the '<em><b>Ident</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IDENT__IDENT = eINSTANCE.getIdent_Ident();

    /**
     * The meta object literal for the '{@link beleg.s78154S78236.impl.EVarImpl <em>EVar</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see beleg.s78154S78236.impl.EVarImpl
     * @see beleg.s78154S78236.impl.S78154S78236PackageImpl#getEVar()
     * @generated
     */
    EClass EVAR = eINSTANCE.getEVar();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVAR__VARIABLE = eINSTANCE.getEVar_Variable();

  }

} //S78154S78236Package
