/*
 * generated by Xtext 2.13.0
 */
package beleg.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractS78154S78236ScopeProvider extends DelegatingScopeProvider {
}
